syntax = "proto3";

package auth;

option go_package = "./auth";

//Сервис аутентификации:

service Auth {
  rpc Login(LoginRequest) returns (LoginReply);
  rpc CheckAuth(CheckAuthRequest) returns (CheckAuthResponse);
  rpc Logout(LogoutRequest) returns (LogoutResponse);
}

// Запрос и ответ для функционала входа (Login):
message LoginRequest {
  string login = 1;
  string password = 2;
}

message LoginReply {
  string token = 1;
}

// Запрос и ответ для функционала проверки входа/токена (CheckAuth): 
message CheckAuthRequest {
    string token = 1;
}

message CheckAuthResponse {
    bool is_auth = 1; 
    string admin_id = 2; 
    string login = 3;
}


// Запрос и ответ для функционала выхода из сессии (Logout):
message LogoutRequest {
    string token = 1;
}

message LogoutResponse {
    bool is_logout = 1;
}
